### ISSUE TITLE
🔥 React & Redux group project: set up your Kanban boardx

### ISSUE THREAD

**Issue by roniy68** [roniy68/spaceX#26]
# Highlights 🥇 

<img src="https://media0.giphy.com/media/CoG8AbJ9oBmOdPuF1L/giphy.gif"/>

✅ Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] React Group Project](https://github.com/microverseinc/curriculum-react-redux/projects/1) board.
✅ Make sure that in the card titles you can see categories: Setup, Fetch data, Lists render, Actions, Conditional components, Filters.
✅ Make sure that each card starts with [Xpt] - that number indicates the number of points that shows how complex the task is. 1 point = 1 hour of work.
✅ Our group includes two people - remove all cards with Team3 in the title.

## Authors 🔆 
---
***Ahmed Hasan Rony***
## @roniy68
***Nwadinigwe Victor chiemerie***
### [ Project Here ](https://github.com/roniy68/spaceX/projects/1)

***NOTE: please add @roniy68 or @Victor-chiemerie in your comment so that***
  ...
## Missed anything?
- [ ] Explained the purpose of this issue.
- [ ] Self reviewed the issue.
- [ ] Added or updated test cases.
- [ ] Informed of breaking changes, testing and migrations (if applicable).
- [ ] Updated documentation (if applicable).
- [ ] Attached screenshots (if applicable).

## Followed Rules: 
- Made sure [no linter errors](https://github.com/microverseinc/linters-config)
-  Followed [Github Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md)
-  Documented [professionaly](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)
-  Followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
-  Followed our list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @roniy68 and @Victor-chiemerie, 

To highlight 👍🏽 
✔️ All required cards are on the board
✔️ Cards are assigned fairly
✔️ Issue is very descriptive

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- I suggest that you close all issues that you would not be addressing in this project such as issues for student 3 as this would help your codebase appear more professional

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDQzY2NiYzNhNWY5OGRhZTc2MGU3ZGZjMzI1ZDQ2OTY4NWVkYjFkNSZjdD1n/ZdUnQS4AXEl1AERdil/giphy.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by roniy68** [comment]
# Thanks @Ghiftee 

## Happy Coding 😄
